config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  devise_for :users
  root to: 'homes#top'
  get 'home/about'  => "homes#about"
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index,] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  get '/search' => 'searches#search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy


  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

 validates :title, presence: true
 validates :body, presence: true, length: { maximum: 200 }

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  attachment :profile_image

  validates :name, uniqueness: true, presence: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

   def configure_permitted_parameters
    added_attrs = [:name, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
   end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
	before_action :authenticate_user!

	def create
		@book = Book.find(params[:book_id])
		@book_comment = BookComment.new(book_comment_params)
		@book_comment.book_id = @book.id
		@book_comment.user_id = current_user.id
		if @book_comment.save
			render :create
		else
		  render 'books/show'
		end
	end

	def destroy
		@book = Book.find(params[:book_id])
  		@book_comment = @book.book_comments.find(params[:id])
		@book_comment.destroy
		render :destroy
	end

	private
	def book_comment_params
		params.require(:book_comment).permit(:comment, :book_id, :user_id)
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user
    @book_comment = BookComment.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

   private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.new(user_id: current_user.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.find_by(user_id: current_user.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end


end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @model = params["search"]["model"]
    @value = params["search"]["value"]
    @how = params["search"]["how"]
    @datas = search_for(@how, @model, @value)
  end

  private

  def match(model, value)
    if model == 'user'
      User.where(name: value)
    elsif model == 'book'
      Book.where(title: value)
    end
  end

  def forward(model, value)
    if model == 'user'
      User.where("name LIKE ?", "#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "#{value}%")
    end
  end

  def backward(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}")
    end
  end

  def partical(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}%")
    end
  end

  def search_for(how, model, value)
    case how
    when 'match'
      match(model, value)
    when 'forward'
      forward(model, value)
    when 'backward'
      backward(model, value)
    when 'partical'
      partical(model, value)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_comment.html.erb
<table id="comments_area">
  <% @book.book_comments.each do |book_comment| %>
    <% book_comment_user = book_comment.user %>
    <tr>
    	<td>
    		<%= link_to user_path(book_comment_user), class: "user_#{book_comment_user.id}" do %>
      		<%= attachment_image_tag book_comment_user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %><br>
      		<%= book_comment_user.name %>
    		<% end %>
    	</td>
    	<td><%= book_comment.comment %></td>
    	<% if current_user == book_comment_user %>
      	<td><%= link_to 'Destroy', book_book_comment_path(book_comment.book_id, book_comment.id), class: 'btn-sm btn-danger', method: :delete, remote: true %></td>
    	<% end %>
    </tr>
  <% end %>
</table>

app/views/book_comments/_form.html.erb
 <%= form_with model:[@book,@book_comment], remote: true do |f| %>
    <%= f.text_area :comment, size:"90x5" %><br>
    <%= f.submit '送信'%>
<% end %>

app/views/book_comments/_index.html.erb
<table id="comments_area">
  <% @book.book_comments.each do |book_comment| %>
    <% book_comment_user = book_comment.user %>
    <tr>
    	<td>
    		<%= link_to user_path(book_comment_user), class: "user_#{book_comment_user.id}" do %>
      		<%= attachment_image_tag book_comment_user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %><br>
      		<%= book_comment_user.name %>
    		<% end %>
    	</td>
    	<td><%= book_comment.comment %></td>
    	<% if current_user == book_comment_user %>
      	<td><%= link_to 'Destroy', book_book_comment_path(book_comment.book_id, book_comment.id), class: 'btn-sm btn-danger', method: :delete, remote: true %></td>
    	<% end %>
    </tr>
  <% end %>
</table>

app/views/book_comments/create.js.erb
$("#comments_area").html("<%= j(render 'book_comments/index', locals: { book_comment: @book_comment }) %>")
$("textarea").val('')

app/views/book_comments/destroy.js.erb
$("#comments_area").html("<%= j(render 'book_comments/index', locals: { book_comment: @book_comment }) %>")
$("textarea").val('')

app/views/books/_list.html.erb
<div class='col-md-3'>
        <h2>User info</h2>
        <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
      <table class='table'>
        <tr></tr>

        <tr>
          <th>name</th>
	        <th><%= user.name %></th>
        </tr>

        <tr>
      	  <th>introduction</th>
      	  <th><%= user.introduction %></th>
        </tr>

        <tr>
          <th>follows</th>
          <th>
            <%= link_to user_followings_path(user.id), method: :get do %>
            <%= user.followings.count %>
            <% end %>
          </th>
        </tr>

        <tr>
          <th>followers</th>
          <th>
            <%= link_to user_followers_path(user.id), method: :get do %>
            <%= user.followers.count %>
            <% end %>
            </th>
        </tr>

      </table>

      <div class='row'>
      <% if current_user == user %>
          <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
      <% else %>
        <% if current_user.following?(user) %>
          <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-info" %>
        <% else %>
          <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
        <% end %>
      <% end %>
      </div>

      <h2 class="mt-3">New book</h2>
        <%= form_with model:book, local:true do |f| %>
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: "form-control book_title" %>
          </div>
          <div class="form-group">
            <%= f.label :opinion %>
            <%= f.text_area :body, class: "form-control book_body" %>
          </div>
          <div class="form-group">
            <%= f.submit 'Create Book', class: "btn btn-success" %>
          </div>
        <% end %>
</div>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		  <% if @book.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h2>
            <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

    	<%= form_with model:@book, local: true do |f| %>
        <div class="form-group">
          <%= f.label :title%>
          <%= f.text_field :title, class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <%= f.label :opinion %>
          <%= f.text_area :body, class: "form-control book_body" %>
        </div>
        <div class="form-group">
          <%= f.submit"Update Book", class: "btn btn-success" %>
        </div>
        <% end %>

       <%= link_to "Show", book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to "Back", books_path, class: "back" %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<main>

    <div class='container px-5 px-sm-0'>


        <% if @book.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
            <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
         <div class='row'>

<%= render 'books/list', book: @book, user: @user %>
        <div class='col-md-8 offset-md-1'>
          <h2>Books</h2>
          <table class='table table-hover table-inverse'>
              <thead>
                <tr>
                  <th></th>
                  <th>Title</th>
                  <th>Opinion</th>
                  <th colspan="3"></th>
                </tr>
              </thead>

              <tbody>
               <% @books.each do |book| %>
               <tr>
                 <td><%= link_to user_path(book.user) do %>
                     <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
                     <% end %>
                 </td>
                 <td><%= link_to book.title, book_path(book) %></td>
                 <td><%= book.body %></td>
                 <td class=<%= "book_" + book.id.to_s %>>
                   <%= render "favorites/favorite-btn", book: book %>
                 </td>
                 <td>コメント数：<%= book.book_comments.count %></td>
               </tr>

               <% end %>
              </tbody>
          </table>
        </div>
      </div>
   </div>
</main>

app/views/books/new.html.erb
<h1>New Book</h1>
<%= form_with model: @book, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
  <div class='container'>
    <div class='row'>
      <%= render 'books/list', book: @book_new, user: @user %>
        <div class='col-md-8 offset-md-1'>
          <h2>Book detail</h2>
            <table class='table'>
              <tbody>
                <tr>
                  <td><%= link_to user_path(@user) do %>
                    <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
                    <br>
                    <%= @user.name %>
                    <% end %>
                  </td>
                  <td><%= link_to @book.title, book_path(@book.id) %></td>
                  <td><%= @book.body %></td>
                  <td class=<%= "book_" + @book.id.to_s %>>
                    <%= render "favorites/favorite-btn", book: @book %>
                  </td>
                  <td>コメント数: <%= @book.book_comments.count %></td>
                  <% if @book.user == current_user %>
                    <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
                    <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
                  <% end %>
                </tr>
              </tbody>
        </table>
        <%= render 'book_comments/index', book: @book, book_comment: @book_comment %>
        <%= render 'book_comments/form', book: @book, book_comment: @book_comment %>
      </div>
    </div>
  </div>

app/views/favorites/_favorite-btn.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
   <span class= "fas fa-heart heart_red"><%= book.favorites.count %></span>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
  <span class= "fas fa-heart heart_blue"><%= book.favorites.count %></span>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$( ".book_" + <%= @book.id %>).html("<%= j(render partial: 'favorites/favorite-btn', locals: {book: @book}) %>");

app/views/favorites/destroy.js.erb
 $(".book_" + <%= @book.id %>).html("<%= escape_javascript(render partial: 'favorites/favorite-btn', locals: {book: @book}) %>");

app/views/homes/about.html.erb
  <div class="container">
    <div class="row">
      <div class='px-3 mx-auto'>
        <h1>Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
      </div>
    </div>
  </div>

app/views/homes/top.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
        <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
        <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
          </div>
          <div class="row">
            <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/relationships/followers.html.erb
<div class='col-md-12 offset-md-1'>
          <h2>Follower Users</h2>
          <table class='table table-hover table-inverse'>
              <% if @users.exists? %>
              <thead>
                <tr>
                  <th>image</th>
                  <th>name</th>
                  <th></th>
                  <th colspan="3"></th>
                </tr>
              </thead>

              <tbody>
               <% users.each do |user| %>
               <tr>
                 <td><%= link_to user_path(user) do %>
                     <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
                     <% end %>
                 </td>
                 <td><%= user.name %></td>
                 <td>フォロー数：<%= user.followings.count %></td>
                 <td>フォロワー数：<%= user.followers.count %></td>
                 <td><%= link_to "Show", user_path(user) %></td>
               </tr>

               <% end %>
               <% else %>
                   <p>ユーザーはいません</p>
               <% end %>
              </tbody>
          </table>
        </div>

app/views/relationships/followings.html.erb
<div class='col-md-12 offset-md-1'>
          <h2>Following Users</h2>
          <table class='table table-hover table-inverse'>
              <% if @users.exists? %>
              <thead>
                <tr>
                  <th>image</th>
                  <th>name</th>
                  <th></th>
                  <th colspan="3"></th>
                </tr>
              </thead>

              <tbody>
               <% users.each do |user| %>
               <tr>
                 <td><%= link_to user_path(user) do %>
                     <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
                     <% end %>
                 </td>
                 <td><%= user.name %></td>
                 <td>フォロー数：<%= user.followings.count %></td>
                 <td>フォロワー数：<%= user.followers.count %></td>
                 <td><%= link_to "Show", user_path(user) %></td>
               </tr>

               <% end %>
               <% else %>
                 <p>ユーザーはいません</p>
               <% end %>
              </tbody>
          </table>
        </div>

app/views/searches/search.html.erb
<div class="container">
  <div class="col-xs-12">
    <% if @model == "user" %>
    <h2>Users search for '<%= @value %>'</h2>
    <table class="table">
        <thead>
            <tr>
                <th></th>
                <th>Name</th>
                <th>Introduction</th>
            </tr>
        </thead>
    <% @datas.each do |user| %>
        <tbody>
            <tr>
                <th>
                    <%= attachment_image_tag(user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40') %>
                </th>
                <th>
                    <%= user.name %>
                </th>
                <th>
                    <%= user.introduction %>
                </th>
            </tr>
        </tbody>
    <% end %>
    <% elsif @model == "book" %>
    <h2>Books search for '<%= @value %>'</h2>
    <table class="table">
        <thead>
            <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
            </tr>
        </thead>
        <% @datas.each do |book| %>
        <tbody>
            <tr>
                <th>
                    <%= attachment_image_tag(book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40') %>
                </th>
                <th>
                    <%= book.title %>
                </th>
                <th>
                    <%= book.body %>
                </th>
            </tr>
        </tbody>
        <% end %>
    <% end %>
    </table>
  </div>
</div>

app/views/users/edit.html.erb
<main>

  <p id="notice"></p>
    <div class='container'>
      <div class='row'>
        <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
          <h2>User info</h2>

        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this obj from being saved:</h2>
            <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

          <%= form_with model:@user, local:true do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前", class: "form-control name" %>
          </div>
          <div class="form-group">
            <label for="user_image">Image</label>
            <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "form-control-file user_image" %>
          </div>
          <div class="form-group">
            <%= f.label :introduction %>
            <%= f.text_area :introduction, id:"inputIntroduction", plaseholder: "自己紹介", class: "form-control introduction" %>
          </div>
          <div class="form-group">
            <%= f.submit "Update User", class: "btn btn-secondary" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
</main>

app/views/users/index.html.erb
<main>
    <div class='container px-5 px-sm-0'>
      <div class='row'>
<%= render 'books/list', book: @book, user: @user %>
        <div class='col-md-8 offset-md-1'>
          <h2>Users</h2>
          <table class='table'>
              <thead>
                <tr>
                  <th>image</th>
                  <th>name</th>
                  <th colspan="3"></th>
                </tr>
              </thead>

              <tbody>
               <% @users.each do |user| %>
               <tr>
                 <td>
                    <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
                 </td>
                 <td><%= user.name %></td>
                 <td>フォロー数：<%= user.followings.count %></td>
                 <td>フォロワー数：<%= user.followers.count %></td>
                 <td>
                    <% unless current_user == user %>
                      <% if current_user.following?(user) %>
                        <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete %>
                      <% else %>
                        <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
                      <% end %>
                    <% end %>
                 </td>
                 <td><%= link_to "Show", user_path(user), class: "user_#{@book.id}" %></td>
               </tr>

               <% end %>
              </tbody>
          </table>
        </div>
      </div>
   </div>
</main>

app/views/users/show.html.erb
<main>

    <div class='container px-5 px-sm-0'>
      <div class='row'>
<%= render 'books/list', book: @book, user: @user %>
        <div class='col-md-8 offset-md-1'>
          <h2>Books</h2>
          <table class='table table-hover table-inverse'>
              <thead>
                <tr>
                  <th></th>
                  <th>Title</th>
                  <th>Opinion</th>
                  <th colspan="3"></th>
                </tr>
              </thead>

              <tbody>
               <% @books.each do |book| %>
               <tr>
                 <td><%= link_to user_path(book.user) do %>
                     <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
                     <% end %>
                 </td>
                 <td><%= link_to book.title, book_path(book) %></td>
                 <td><%= book.body %></td>
                 <td>コメント数：<%= book.book_comments.count %></td>
               </tr>

               <% end %>
              </tbody>
          </table>
        </div>
      </div>
   </div>
</main>

app/views/users/show_followers.html.erb
<div class='col-md-12 offset-md-1'>
          <h2>Follower Users</h2>
          <table class='table table-hover table-inverse'>
              <thead>
                <tr>
                  <th>image</th>
                  <th>name</th>
                  <th></th>
                  <th colspan="3"></th>
                </tr>
              </thead>

              <tbody>
               <% @users.each do |user| %>
               <tr>
                 <td><%= link_to user_path(user) do %>
                     <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
                     <% end %>
                 </td>
                 <td><%= user.name %></td>
                 <td><%= user.followings.count %></td>
                 <td><%= user.followers.count %></td>
                 <td><%= link_to "Show", user_path(user), class: "user_#{@book.id}" %></td>
               </tr>

               <% end %>
              </tbody>
          </table>
        </div>

app/views/users/show_followings.html.erb
<div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>